# 配置项目启动时的端口号
server:
  port: 8080


# 数据库连接配置
spring:
  datasource:
   url: jdbc:mysql://192.168.190.131:3306/book_test?characterEncoding=utf8&useSSL=false
   username: root
   password: 123
   driver-class-name: com.mysql.cj.jdbc.Driver

# 设置 Mybatis 的 xml 保存路径
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration: # 配置打印 Mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #自动驼峰转换

kaptcha:
  image:
    width: 200
    height: 50
  text-producer:
    font:
      size: 40
  items:
    admin:
      path: /admin/captcha
      session:
        key: HOME_KAPTCHA_SESSION_KEY
        date: HOME_KAPTCHA_SESSION_DATE
